name: A5C

# Universal event triggers - the agent router will handle filtering
on:
  # Pull Request Events
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main, develop, master]

  # Push Events
  push:
    branches: [main, develop, master]

  # Issue Events
  issues:
    types: [opened, edited, labeled]

  # Issue Comment Events
  issue_comment:
    types: [created, edited]

  # Scheduled Events
  schedule:
    # Every 30 minutes
    - cron: '*/30 * * * *'
  workflow_run:
    types: [completed]
    workflows: [Build, Deploy, Tests, Release, E2E Tests]

  # Manual Triggers
  workflow_dispatch:
    inputs:
      agent_uri:
        description: 'Specific agent to run (optional - leave empty for auto-routing)'
        required: false
      debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean

jobs:
  # Single job that handles all agent routing and execution
  a5c:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Filter Self Workflow-run
        id: filter-self
        # in case this is a workflow_run event, skip if the workflow did not fail.
        if: github.event_name == 'workflow_run' && (github.event.workflow_run.conclusion != 'failure' || github.event.workflow_run.head_branch != 'main')
        run: |
          echo "::set-output name=skip::true"
          exit 0
      - name: Run A5C
        id: agents
        uses: a5c-ai/action@main
        if: steps.filter-self.outputs.skip != 'true'
        with:
          # Auto-routing by default, unless specific agent is requested
          agent_uri: ${{ github.event.inputs.agent_uri || '' }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DISABLE_AUTOUPDATER: 1
          CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC: 1
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          DEBUG: ${{ github.event.inputs.debug || 'false' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ vars.DISCORD_GUILD_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN || '' }}
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID || '' }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID || '' }}