# GitHub action to build

name: Deploy
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true
on:
  push:
    branches:
      - main
      - a5c/main
      - release
env:
    DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    NEXTAUTH_URL: http://localhost:4002
    NEXTAUTH_SECRET: secret
    NEXTAUTH_SESSION_STRATEGY: database
    AUTH_PROVIDERS: github,credentials,saml,idp-initiated
    FEATURE_TEAM_SSO: true
    FEATURE_TEAM_DSYNC: true
    FEATURE_TEAM_AUDIT_LOG: true
    FEATURE_TEAM_WEBHOOK: false
    FEATURE_TEAM_API_KEY: true
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    AZURE_OPENAI_PROJECT_NAME: ${{ vars.AZURE_OPENAI_PROJECT_NAME || '' }}
    AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY || '' }}
    # azure credentials
    AZURE_APPLICATION_CLIENT_ID: ${{ vars.AZURE_APPLICATION_CLIENT_ID || '' }}
    AZURE_APPLICATION_CLIENT_SECRET: ${{ secrets.AZURE_APPLICATION_CLIENT_SECRET || '' }}
    AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID || '' }}
    AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID || '' }}
    AZURE_RESOURCE_GROUP_NAME: ${{ vars.AZURE_RESOURCE_GROUP_NAME || '' }}    
    AZURE_ACR_NAME: ${{ vars.AZURE_ACR_NAME || '' }}
    AZURE_AKS_CLUSTER_NAME: ${{ vars.AZURE_AKS_CLUSTER_NAME || '' }}
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || '' }}
    FEATURE_TEAM_DELETION: true
    FEATURE_TEAM_PAYMENTS: true
    CONFIRM_EMAIL: false
    HIDE_LANDING_PAGE: false
    GROUP_PREFIX: a5c-
    DISABLE_NON_BUSINESS_EMAIL_SIGNUP: false
    APP_URL: http://localhost:4002
    JACKSON_PRODUCT_ID: a5c
    JACKSON_WEBHOOK_SECRET: your-webhook-secret
    JACKSON_API_KEY: secret
    DEBUG: pw:webserver
    CI: true
    # vercel credentials
    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN || '' }}
    VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID || '' }}
    VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID || '' }}      
    # supabase credentials
    SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN || '' }}
    SUPABASE_ORG_ID: ${{ vars.SUPABASE_ORG_ID || '' }}
    SUPABASE_PROJECT_REF: ${{ vars.SUPABASE_PROJECT_REF || '' }}
    SUPABASE_PROJECT_URL:  ${{ vars.SUPABASE_PROJECT_URL || '' }}
    SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD || '' }}
    # slack credentials
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN || '' }}
    SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET || '' }}
    SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN || '' }}
    # discord credentials
    DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN || '' }}
    DISCORD_GUILD_ID: ${{ vars.DISCORD_GUILD_ID || '' }}      
    # access key for stripe api for management
    STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY || '' }}
    # access key for stripe api for payments
    STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY || '' }}
    # webhook secret for stripe
    STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET || '' }}
    # webhook url for stripe
    STRIPE_WEBHOOK_URL: ${{ vars.STRIPE_WEBHOOK_URL || '' }}
    # webhook id for stripe
    STRIPE_WEBHOOK_ID: ${{ vars.STRIPE_WEBHOOK_ID || '' }}
    # aws credentials 
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID || '' }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY || '' }}
    AWS_REGION: ${{ vars.AWS_REGION || '' }}
    # gcloud credentials
    GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS || '' }}    

    # auth credentials
    GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID || '' }}
    GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET || '' }}
    AUTH_GITHUB_CLIENT_ID: ${{ secrets.AUTH_GITHUB_CLIENT_ID || '' }}
    AUTH_GITHUB_CLIENT_SECRET: ${{ secrets.AUTH_GITHUB_CLIENT_SECRET || '' }}
    AUTH_GITHUB_ORG_ID: ${{ vars.AUTH_GITHUB_ORG_ID || '' }}
    AUTH_GITHUB_ORG_NAME: ${{ vars.AUTH_GITHUB_ORG_NAME || '' }}
    AUTH_GITHUB_ORG_DESCRIPTION: ${{ vars.AUTH_GITHUB_ORG_DESCRIPTION || '' }}

    # other credentials
    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY || '' }}
    HEROKU_APP_NAME: ${{ vars.HEROKU_APP_NAME || '' }}
    HEROKU_APP_ID: ${{ vars.HEROKU_APP_ID || '' }}
    HEROKU_APP_URL: ${{ vars.HEROKU_APP_URL || '' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        continue-on-error: true
        with:
          node-version: 22
          cache: 'npm'
          check-latest: true
      - name: Setup Python
        uses: actions/setup-python@v4
        continue-on-error: true
        with:
          python-version: 3.12
          cache: 'pip'
          check-latest: true
      - run: ./scripts/deploy.sh
